// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"context"
	"github.com/tuancamtbtx/learning-go/app/server"
	"github.com/tuancamtbtx/learning-go/handlers/grpc"
)

// Injectors from build_server.go:

func buildServer(ctx context.Context) (*server.Server, error) {
	productServiceHandler := grpc.NewProductServiceHandler()
	grpcServer, err := server.NewGrpcServer(productServiceHandler)
	if err != nil {
		return nil, err
	}
	serverServer := server.NewServer(grpcServer)
	return serverServer, nil
}
